#!/bin/sh

mkdir -p opk
cp ./sdlgnuboy.elf opk/sdlgnuboy.elf
cp ./icon.png opk/icon.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Game boy
Comment=Game boy emulator
Exec=sdlgnuboy.elf %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.retrostone.desktop

mksquashfs ./opk gnuboy_retrostone.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
